version: '3.3'

services:
  mysql:
    image: mariadb:11.3
    deploy:
      resources:
        limits:
          memory: 1536M  # Set the memory limit as needed
        reservations:
          memory: 1536M  # Set the reserved memory as needed
    restart: always
    container_name: misp-mysql
    tmpfs:
      - /tmp
    volumes:
      - ./misp-db-data/mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: misp
      MYSQL_USER: misp
      MYSQL_PASSWORD: password # Please change for production
      MYSQL_ROOT_PASSWORD: password # Please change for production
    networks:
      - iris_backend
      - iris_frontend

  redis:
    image: redis:7.2
    deploy:
      resources:
        limits:
          memory: 512M  # Set the memory limit as needed
        reservations:
          memory: 512M  # Set the reserved memory as needed
    restart: always
    container_name: misp-redis
    volumes:
      - ./misp-redis-data/redis_data:/data
    networks:
      - iris_backend
      - iris_frontend

  misp-modules:
    image: ghcr.io/nukib/misp-modules:latest
    restart: always
    container_name: misp-modules
    cap_drop:
      - NET_RAW
      - SYS_CHROOT
      - MKNOD
      - NET_BIND_SERVICE
      - AUDIT_WRITE
      - SETFCAP
    networks:
      - iris_backend
      - iris_frontend

  misp:
    image: ${MISP_IMAGE-ghcr.io/nukib/misp:latest}
    deploy:
      resources:
        limits:
          memory: 1536M  # Set the memory limit as needed
        reservations:
          memory: 1536M  # Set the reserved memory as needed
    restart: always
    container_name: misp
    depends_on:
      - mysql
      - redis
    tmpfs:
      - /tmp
    cap_drop:
      - NET_RAW
      - SYS_CHROOT
      - MKNOD
      - AUDIT_WRITE
      - SETFCAP
    environment:
      MYSQL_HOST: mysql
      MYSQL_LOGIN: misp
      MYSQL_PASSWORD: password # Please change for production
      MYSQL_DATABASE: misp
      REDIS_HOST: redis
      MISP_BASEURL: https://ircmm.armada247.com:5602
      MISP_UUID: 0a674a5a-c4cb-491d-80cf-5adb48b5c1cd # Please change for production
      MISP_ORG: Testing org # Please change for production
      MISP_MODULE_URL: http://misp-modules
      MISP_EMAIL: ahoj@example.com # Please change for production
      SECURITY_SALT: PleaseChangeForProduction # Please change for production
      ZEROMQ_ENABLED: yes
      SYSLOG_ENABLED: no
      ECS_LOG_ENABLED: yes
      MISP_DEBUG: yes
    volumes:
      - ./misp-core-data/misp_logs:/var/www/MISP/app/tmp/logs/
      - ./misp-core-data/misp_certs:/var/www/MISP/app/files/certs/
      - ./misp-core-data/misp_attachments:/var/www/MISP/app/attachments/
      - ./misp-core-data/misp_img_custom:/var/www/MISP/app/files/img/custom/
      - ./misp-core-data/misp_gnupg:/var/www/MISP/.gnupg/
    ports:
      - "8081:80"
      - "5605:50000"
    networks:
      - iris_backend
      - iris_frontend
